### ISSUE TITLE
Allow skipping builds before e2e

### ISSUE THREAD

**Issue by mvarendorff** [Yes-Theory-Fam/yestheory.family#253]
See https://github.com/Yes-Theory-Fam/yestheory.family/pull/252/commits/fe43339897e52cb8aaf3a61d711eec36ddec5727 for setup.

Needs a long term solution on cron trigger to make sure retagged versions are cleaned up as well.

Use 
```yml
on:
  pull_request:
    types:
      - closed
```
as trigger on a new workflow to clean up tagged versions with the existing clean job.
